---
- hosts: one
  tasks:
  - name: Install required packages
    apt: pkg={{item}}
    with_items:
      - tgt
    sudo: yes
  - name: Creating osd pool iscsi
    ceph_osd_pool: state=present name=iscsi pgnum=128 pgpnum=128
    register: add_result
  - debug: var=add_result
  - name: Creating RBD image iscsi-rbd
    ceph_rbd: name=iscsi-rbd state=present size={{rbd_size}} pool=iscsi
    register: rbd_create
  - debug: var=rbd_create
  - name: Adding Target
    lineinfile: dest=/etc/tgt/targets.conf insertafter=EOF line='<target {{target_ip}}:iscsi>'
    lineinfile: dest=/etc/tgt/targets.conf insertafter=EOF line='\tdriver iscsi\n\tbs-type rbd\n\tbacking-store iscsi/iscsi-rbd\n\tinitiator-address {{target_ip}}\n</target>'
  - name: Updating TGT service
    service: name=tgt state=restarted