---
- hosts: one
  tasks:
  - name: Install required packages
    apt: pkg={{item}}
    with_items:
      - tgt
    sudo: yes
  - name: Creating osd pool iscsi
    ceph_osd_pool: state=present name=iscsi.{{item}} pgnum=32 pgpnum=32
    register: add_result
    with_items:
      - "1"
      - "2"
      - "3"
  - debug: var=add_result
  - name: Creating RBD image iscsi-rbd.{{item}}
    ceph_rbd: name=iscsi-rbd.{{item}} state=present size={{rbd_size}} pool=iscsi.{{item}}
    register: rbd_create
    with_items:
      - "1"
      - "2"
      - "3"    
  - debug: var=rbd_create
  - name: Adding Target
    sudo: yes
    template: src=./iscsi.j2 dest=/etc/tgt/conf.d/iscsi-{{item}}.conf
    with_items:
      - "1"
      - "2"
      - "3"  
  - name: Updating TGT service
    sudo: yes
    service: name=tgt state=restarted
